---
    cidr_networks: &cidr_networks
      container: 172.21.0.0/22
      tunnel: 172.21.4.0/22
      storage: 172.21.8.0/22 #Subnet is /22, but we only require a few hosts so we a small part it to avoid excluding many ips

    used_ips:
      - "172.21.1.1,172.21.1.254"

    global_overrides:
      cidr_networks: *cidr_networks
      internal_lb_vip_address: 172.21.1.254
      #
      # The below domain name must resolve to an IP address
      # in the CIDR specified in haproxy_keepalived_external_vip_cidr.
      # If using different protocols (https/http) for the public/internal
      # endpoints the two addresses must be different.
      #
      external_lb_vip_address: vip.example.com

      management_bridge: "br-mgmt"
      provider_networks:
        - network:
            container_bridge: "br-mgmt"
            container_type: "veth"
            container_interface: "eth1"
            ip_from_q: "container"
            type: "raw"
            group_binds:
              - all_containers
              - hosts
            is_container_address: true
        - network:
            container_bridge: "br-vxlan"
            container_type: "veth"
            container_interface: "eth10"
            ip_from_q: "tunnel"
            type: "vxlan"
            range: "1:1000"
            net_name: "vxlan"
            group_binds:
              - neutron_linuxbridge_agent
        - network:
            container_bridge: "br-vlan"
            container_type: "veth"
            container_interface: "eth11"
            host_bind_override: "bond0"
            type: "vlan"
            range: "13:13,22:22"
            net_name: "vlan"
            group_binds:
              - neutron_linuxbridge_agent
        - network:
            container_bridge: "br-storage"
            container_type: "veth"
            container_interface: "eth2"
            ip_from_q: "storage"
            type: "raw"
            group_binds:
              - glance_api
              - cinder_api
              - cinder_volume
              - manila_share
              - nova_compute
              - ceph-osd

    ###
    ### Infrastructure
    ###

    _infrastructure_hosts: &infrastructure_hosts
      os-infra-c-01:
        ip: 172.21.1.10
      os-infra-d-01:
        ip: 172.21.1.11
      os-infra-e-01:
        ip: 172.21.1.12

    # nova hypervisors
    compute_hosts: &compute_hosts
      compute01:
        ip: 172.21.1.20
      compute02:
        ip: 172.21.1.21



    # galera, memcache, rabbitmq, utility
    shared-infra_hosts: *infrastructure_hosts

    # repository (apt cache, python packages, etc)
    repo-infra_hosts: *infrastructure_hosts

    # load balancer
    # Ideally the load balancer should not use the Infrastructure hosts.
    # Dedicated hardware is best for improved performance and security.
    haproxy_hosts: *infrastructure_hosts

    ###
    ### OpenStack
    ###

    # keystone
    identity_hosts: *infrastructure_hosts

    # cinder api services
    storage-infra_hosts: *infrastructure_hosts

    # cinder volume hosts (Ceph RBD-backed)
    storage_hosts: *infrastructure_hosts

    # glance
    image_hosts: *infrastructure_hosts

    # placement
    placement-infra_hosts: *infrastructure_hosts

    # nova api, conductor, etc services
    compute-infra_hosts: *infrastructure_hosts

    # heat
    orchestration_hosts: *infrastructure_hosts

    # horizon
    dashboard_hosts: *infrastructure_hosts

    # neutron server, agents (L3, etc)
    network_hosts: *infrastructure_hosts

    # ceilometer (telemetry data collection)
    metering-infra_hosts: *infrastructure_hosts

    # aodh (telemetry alarm service)
    metering-alarm_hosts: *infrastructure_hosts

    # gnocchi (telemetry metrics storage)
    metrics_hosts: *infrastructure_hosts

    # manila (share service)
    #manila-infra_hosts: *infrastructure_hosts
    #manila-data_hosts: *infrastructure_hosts

    # ceilometer compute agent (telemetry data collection)
    metering-compute_hosts: *compute_hosts

    # murano application cataloug
    #murano-infra_hosts: *infrastructure_hosts

    # masaki HA
    # masakari-infra_hosts: *infrastructure_hosts
