---
- hosts: compute_all
  gather_facts: no
  become: true

  tasks:

  - name: install ntp
    apt: name=chrony state=installed update_cache=yes

  - name: write chrony.conf
    copy: src=chrony.conf dest=/etc/chrony/chrony.conf mode=644 owner=root group=root
    notify: restart ntp

  - name: start ntp
    service: name=chrony state=started
    tags: 
       - restart

  handlers:

  - name: restart ntp
    service: name=chrony state=restarted
